# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

sass:
  sass_dir: _sass
  style: compressed

include:
  - _includes/head-custom.html

mermaid: true

